name: ci

on: push  # execute on every push

jobs:
    ci:  # continuos integration job
        runs-on: ubuntu-latest  # 
        steps:
            - uses: actions/checkout@v2 # check the repo
            - uses: actions/setup-node@v2 # setup nodejs
              with:
                node-version: "22"  # use this version
            - name: npm ci  # install dependency
              env:
                CI: true
              run: |
                npm ci
            - name: test  # run test comand
              run: |
                npm test
            - name: deploy  # run test comand
                run: |
                  npm run deploy