name: ci

on: push  # execute on every push

jobs:
    ci:  # continuos integration job
        runs-on: ubuntu-latest  # 
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || 'default-access-key-id' }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || 'default-secret-access-key' }}
                aws-region: us-east-1
            - uses: actions/checkout@v2 # check the repo
            - uses: actions/setup-node@v2 # setup nodejs
              with:
                node-version: "22"  # use this version
            - name: npm ci  # install dependency
              env:
                CI: true
              run: |
                npm ci
            - name: test  # run test comand
              run: |
                npm test
            - name: deploy  # run test comand
              run: |
                npm run deploy